import {z} from 'zod';
import {State,Action} from '../types';
import {randomUUID} from 'node:crypto';
export const actionSchema=z.discriminatedUnion('tool',[
 z.object({tool:z.literal('inventory_update'),args:z.object({id:z.string(),stock:z.number().int().min(0).max(1000000),reason:z.string().min(3).max(300),version:z.number().int()})}),
 z.object({tool:z.literal('price_update'),args:z.object({id:z.string(),price:z.number().int().min(100).max(100000000),version:z.number().int()})}),
 z.object({tool:z.literal('mark_packed'),args:z.object({id:z.string(),version:z.number().int()})}),
 z.object({tool:z.enum(['callback_request','visit_request']),args:z.object({reason:z.string().min(3).max(500),language:z.string().max(40),window:z.string().min(3).max(100),contact:z.string().max(100),related:z.string().max(100).default('')})}),
 z.object({tool:z.literal('pilot_plan'),args:z.object({id:z.string(),units:z.number().int().nonnegative().max(100000)})})]);
export function prepare(state:State,user:string,input:unknown,now=Date.now()):Action{const a=actionSchema.parse(input);const args=a.args as Record<string,unknown>;let version=0,preview='';if(['inventory_update','price_update','pilot_plan'].includes(a.tool)){const p=state.products.find(p=>p.id===args.id&&p.manufacturerId===state.manufacturerId);if(!p)throw new Error('Product not found in your workspace');version=p.version;if(a.tool==='inventory_update'){if(Number(args.stock)<p.reserved)throw new Error('Stock cannot be below reserved units');preview=`Update ${p.name} stock from ${p.stock} to ${args.stock} units? Reason: ${args.reason}`;}else if(a.tool==='price_update')preview=`Change ${p.name} price from ₹${p.price/100} to ₹${Number(args.price)/100}?`;else preview=`Accept a pilot commitment of ${args.units} units for ${p.name}?`;}else if(a.tool==='mark_packed'){const o=state.orders.find(o=>o.id===args.id);if(!o)throw new Error('Order not found');if(o.status!=='ready_to_ship')throw new Error('Only ready-to-ship orders can be packed');version=o.version;preview=`Mark ${o.id} packed? This does not record courier handover.`;}else preview=`Create ${a.tool==='visit_request'?'a cluster visit':'a callback'} request for ${args.window}? ${args.reason}`;
 if('version'in args&&args.version!==version)throw new Error('Record changed. Refresh before updating.');
 const action:Action={id:randomUUID(),user,tool:a.tool,args,version,expires:now+5*60000,status:'pending',preview};state.actions.push(action);state.actions=state.actions.slice(-100);return action;}
export function confirm(state:State,user:string,id:string,now=Date.now()){const a=state.actions.find(a=>a.id===id&&a.user===user);if(!a)throw new Error('Action not found');if(a.status==='done')return a.result!;if(a.status!=='pending'||now>a.expires)throw new Error('Confirmation expired or cancelled. Prepare it again.');const args=a.args;let result='';if(['inventory_update','price_update','pilot_plan'].includes(a.tool)){const p=state.products.find(p=>p.id===args.id&&p.manufacturerId===state.manufacturerId);if(!p||p.version!==a.version)throw new Error('Record changed. Prepare a fresh confirmation.');if(a.tool==='inventory_update'){p.stock=Number(args.stock);result=`Stock updated to ${p.stock} units for ${p.name}.`;}else if(a.tool==='price_update'){p.price=Number(args.price);result=`Price updated for ${p.name}.`;}else{state.pilot={sku:p.id,units:Number(args.units),at:new Date(now).toISOString()};result='Pilot plan saved.';}p.version++;}else if(a.tool==='mark_packed'){const o=state.orders.find(o=>o.id===args.id);if(!o||o.version!==a.version||o.status!=='ready_to_ship')throw new Error('Order changed. Refresh first.');o.status='packed';o.version++;result=`${o.id} is packed. Courier handover is still pending.`;}else{state.support.unshift({id:'REQ-'+randomUUID().slice(0,8),manufacturerId:state.manufacturerId,type:a.tool==='visit_request'?'Cluster visit':'Callback',reason:String(args.reason),language:String(args.language),window:String(args.window),contact:String(args.contact),related:String(args.related??''),status:'Requested',owner:'Unassigned',notes:'',minutes:0,version:1});result='Support request saved. No call or visit has taken place.';}a.status='done';a.result=result;state.activity.unshift({id:randomUUID(),at:new Date(now).toISOString(),text:result});return result;}
