import {State,Product,Order} from './types';
import {forecast} from './forecast/engine';
import {available,filterOrders} from './services';

export type OperatingPlan={contact:string;packingOwner:string;packingCapacity:number;minutesPerParcel:number;ownerMinutes:number;catalogueChecked:boolean;packingChecked:boolean;pickupChecked:boolean;firstOrderChecked:boolean;firstPayoutChecked:boolean;independent:boolean;seasonalConstraint:string;version:number};
export const operatingDefaults:OperatingPlan={contact:'Ananya Rao',packingOwner:'',packingCapacity:0,minutesPerParcel:4,ownerMinutes:30,catalogueChecked:false,packingChecked:false,pickupChecked:false,firstOrderChecked:false,firstPayoutChecked:false,independent:false,seasonalConstraint:'',version:1};
export function operatingPlan(s:State):OperatingPlan{return {...operatingDefaults,...s.operatingPlan};}
export function readiness(s:State){const plan=operatingPlan(s);const checks=[{key:'packingOwner',label:'Named person for physical packing',done:!!plan.packingOwner.trim()},{key:'packingCapacity',label:'Daily parcel capacity agreed',done:plan.packingCapacity>0},{key:'catalogueChecked',label:'First catalogue reviewed',done:plan.catalogueChecked},{key:'packingChecked',label:'Packing and label routine checked',done:plan.packingChecked},{key:'pickupChecked',label:'Pickup arrangement reviewed',done:plan.pickupChecked}];return {plan,checks,ready:checks.every(c=>c.done),completed:checks.filter(c=>c.done).length};}
export type Batch={id:string;sku:string;name:string;variant:string;due:string;orders:Order[];units:number;late:boolean};
export function batches(s:State){const groups=new Map<string,Batch>();for(const o of filterOrders(s,{status:'ready_to_ship'})){const p=s.products.find(p=>p.id===o.sku)!;const id=`B${o.due.replaceAll('-','')}-${p.id.replace('SKU-','')}`;const batch=groups.get(id)??{id,sku:p.id,name:p.name,variant:p.variant,due:o.due,orders:[],units:0,late:o.due<s.date};batch.orders.push(o);batch.units+=o.quantity;groups.set(id,batch);}return [...groups.values()].sort((a,b)=>a.due.localeCompare(b.due)||a.sku.localeCompare(b.sku));}
export function commitment(s:State,p:Product){const setup=readiness(s),f=forecast({...p,horizon:30},s.observations);const own=s.observations.filter(o=>o.sku===p.id&&o.available&&o.day<0&&o.day>=-Math.min(p.age,14));const visits=own.reduce((a,o)=>a+o.visits,0),purchases=own.reduce((a,o)=>a+o.purchases,0),observedUnits=own.reduce((a,o)=>a+o.units,0);const conversion=visits?purchases/visits:null;const supportMinutes=s.support.filter(r=>r.manufacturerId===p.manufacturerId).reduce((a,r)=>a+r.minutes,0);const cashUnits=p.cost&&p.cost>0?Math.floor(p.cash/p.cost):0;const readyUnits=Math.min(available(p),cashUnits);const evidence=visits>=1000&&own.length>=7;let decision:'Test'|'Replenish'|'Hold'|'Pause'='Test',reason='Use existing saleable stock for a bounded test before committing a production line.';let units=Math.min(readyUnits,setup.plan.packingCapacity*7,f.status==='ready'?f.seven.c50:0);const blockers=setup.checks.filter(c=>!c.done).map(c=>c.label);const perUnit=f.status==='ready'&&f.contribution!==null&&f.retained>0?Math.round(f.contribution/f.retained):null;
 if(!setup.ready){decision='Hold';reason='Establish physical fulfilment ownership and the packing routine before activation.';units=0;}
 else if(f.status!=='ready'||!evidence){decision='Hold';reason='Insufficient eligible exposure. Gather more evidence; this does not establish low demand.';units=0;}
 else if(perUnit===null){decision='Hold';reason='Important costs are missing. Review economics before committing more stock.';units=0;}
 else if(perUnit<p.floor){decision='Pause';reason='Projected contribution is below this manufacturer’s own floor. Review costs and assortment.';units=0;}
 else if(conversion!==null&&conversion<.025){decision='Hold';reason='Exposure is adequate but conversion is weak. Review relevance, content and price before producing more.';units=0;}
 else if(f.retained<p.minMonthly){decision='Hold';reason='Projected retained volume is below your minimum worthwhile monthly volume. Review the bounded test before expanding.';units=0;}
 else if(f.seven.c90>setup.plan.packingCapacity*7){decision='Hold';reason='Potential orders exceed the agreed packing capacity. Fix the operating bottleneck before expansion.';units=0;}
 else if(setup.plan.seasonalConstraint.trim()){decision='Hold';reason='A seasonal constraint is recorded. Resolve its impact before releasing additional capacity.';units=0;}
 else if(available(p)<f.seven.c50){decision='Replenish';units=Math.floor(Math.min(f.recommended,p.capacity,cashUnits)/p.batch)*p.batch;reason='Conversion and eligible exposure support a small replenishment, bounded by cash, capacity and batch size.';if(!units){decision='Hold';reason='A practical production batch does not fit the safe commitment. Review batch size or inventory exposure.';}}
 units=Math.max(0,Math.floor(units));return{decision,reason,units,source:decision==='Replenish'?'New production':'Existing saleable stock',cashExposure:units*(p.cost??0),visits,purchases,observedUnits,conversion,evidence,eligibleDays:own.length,setup,forecast:f,perUnit,blockers,supportMinutes,nextEvidence:'Review after 7 eligible days: retained orders, contribution, packing workload and repeatable exposure. Promotional traffic may not persist.',guarantee:'No minimum orders are guaranteed. Test whether bounded exposure is acceptable to this manufacturer.'};}
export function batchManifest(batch:Batch){return batch.orders.map(o=>({batch:batch.id,order:o.id,sku:batch.sku,product:batch.name,variant:batch.variant,quantity:o.quantity,deadline:o.due,status:o.status}));}
export function batchLabels(batch:Batch){return batch.orders.map(o=>`DEMO LABEL | NOT VALID FOR CARRIER USE\nBatch: ${batch.id}\nOrder: ${o.id}\nSKU: ${o.sku}\n${batch.name} | ${batch.variant}\nQuantity: ${o.quantity}\nSample destination: ${o.city}\nNo shipment booked.\n`).join('\n============================\n\n');}
