import {State,Product} from './types';
import {forecast} from './forecast/engine';
export const money=(paise:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(paise/100);
export const number=(n:number)=>new Intl.NumberFormat('en-IN').format(n);
export const sellerProducts=(s:State)=>s.products.filter(p=>p.manufacturerId===s.manufacturerId);
export function filterOrders(s:State,query:Record<string,string>={}){return s.orders.filter(o=>sellerProducts(s).some(p=>p.id===o.sku)).filter(o=>!query.status||query.status==='all'||o.status===query.status).filter(o=>!query.sku||o.sku===query.sku).filter(o=>query.due!=='today'||o.due===s.date).filter(o=>query.due!=='overdue'||(o.due<s.date&&['ready_to_ship','packed'].includes(o.status))).filter(o=>!query.q||`${o.id} ${o.sku} ${s.products.find(p=>p.id===o.sku)?.name}`.toLowerCase().includes(query.q.toLowerCase())).sort((a,b)=>query.sort==='quantity'?b.quantity-a.quantity:a.due.localeCompare(b.due));}
export const available=(p:Product)=>Math.max(0,p.stock-p.reserved);
export function summary(s:State){const orders=filterOrders(s);return{due:orders.filter(o=>o.due===s.date&&o.status==='ready_to_ship').length,overdue:orders.filter(o=>o.due<s.date&&o.status==='ready_to_ship').length,labels:orders.filter(o=>!o.label&&o.status==='ready_to_ship').length,low:sellerProducts(s).filter(p=>available(p)<40).length,packed:orders.filter(o=>o.status==='packed').length,payment:s.payments.filter(p=>p.status==='Expected').reduce((a,p)=>a+p.amount,0)};}
export const completeness=(p:Product)=>Math.round([p.name,p.variant,p.description,p.image,p.price>0,p.category].filter(Boolean).length/6*100);
export function interventions(s:State){return s.products.flatMap(p=>{const f=forecast(p,s.observations);return (f.status==='ready'?f.constraints:[f.reason]).map((trigger,i)=>({id:`${p.id}-${i}`,manufacturerId:p.manufacturerId,sku:p.id,trigger,metric:f.status==='ready'?`${f.unmet} unmet units; ${f.eligibleDays} eligible days`:'Limited evidence',action:trigger.includes('Contribution')?'Review costs before expanding':'Review with operating owner',owner:s.manufacturers.find(m=>m.id===p.manufacturerId)!.owner,due:s.date,status:'Open'}));});}
