import {describe,it,expect} from 'vitest';
import {seed} from '../src/lib/fixtures';
import {quickIntent,orderReferences} from '../src/lib/assistant/quick';
import {confirm,prepare} from '../src/lib/assistant/actions';
import {batches} from '../src/lib/launch';
import {cleanSpeech,cleanReply,ReplyTextStream,takeSentences,lines} from '../src/lib/stream';
describe('direct conversational work',()=>{
 it('answers today from the actual order records',()=>{const state=seed();const intent=quickIntent(state,'Aaj kitne orders bhejne hain?')!;expect(intent.kind).toBe('read');const result=intent.run(state,'user','hi');expect(result.text).toContain('आज 4');expect(result.records).toHaveLength(4);expect(state.actions).toHaveLength(0);});
 it('uses the same low-stock threshold as the daily queue',()=>{const s=seed();const r=quickIntent(s,'Which products are running low?')!.run(s,'user','en');expect(r.records).toHaveLength(2);});
 it('supports spoken English and Hindi order references without guessing',()=>{expect(orderReferences('Orders LP eight zero four two and 8047')).toEqual(['LP-8042','LP-8047']);expect(orderReferences('ऑर्डर एल पी ८०४२')).toEqual(['LP-8042']);});
 it('prepares several orders without changing their status',()=>{const state=seed();const result=quickIntent(state,'I have prepared orders LP 8042 and LP 8047')!.run(state,'user','en');expect(result.action?.tool).toBe('orders_packed');expect(state.orders.find(o=>o.id==='LP-8042')?.status).toBe('ready_to_ship');confirm(state,'user',result.action!.id);for(const id of ['LP-8042','LP-8047'])expect(state.orders.find(o=>o.id===id)?.status).toBe('packed');expect(confirm(state,'user',result.action!.id)).toContain('2 orders');expect(state.activity).toHaveLength(1);});
 it('asks which orders rather than treating all orders as prepared',()=>{const state=seed();const result=quickIntent(state,'I have prepared the orders')!.run(state,'user','en');expect(result.action).toBeUndefined();expect(result.choices?.length).toBeGreaterThan(0);expect(state.actions).toHaveLength(0);});
 it('does not interpret spoken yes as confirmation',()=>{expect(quickIntent(seed(),'yes confirm it')).toBeNull();});
 it('blocks unknown orders before preparing any update',()=>{const state=seed();expect(()=>quickIntent(state,'I have prepared orders LP 8042 and LP 9999')!.run(state,'user','en')).toThrow('not found');expect(state.actions).toHaveLength(0);expect(state.orders.find(o=>o.id==='LP-8042')?.status).toBe('ready_to_ship');});
 it('rejects a stale multi-order review before touching any order',()=>{const state=seed();const action=prepare(state,'user',{tool:'orders_packed',args:{ids:['LP-8042','LP-8047']}});state.orders.find(o=>o.id==='LP-8047')!.version++;expect(()=>confirm(state,'user',action.id)).toThrow('Batch changed');expect(state.orders.find(o=>o.id==='LP-8042')?.status).toBe('ready_to_ship');});
 it('deduplicates order references and respects ownership and expiry',()=>{const state=seed();const action=prepare(state,'user',{tool:'orders_packed',args:{ids:['LP-8042','LP-8042']}},100);expect(action.args.orders).toHaveLength(1);expect(()=>confirm(state,'other',action.id,101)).toThrow('not found');expect(()=>confirm(state,'user',action.id,400000)).toThrow('expired');});
 it('handles negated packing and stock requests without preparing',()=>{const state=seed();for(const message of ['Do not mark orders LP 8042 packed','Do not set SKU-101 stock to 50',`Do not mark batch ${batches(state)[0].id} packed`])expect(quickIntent(state,message)!.run(state,'user','en').action).toBeUndefined();expect(state.actions).toHaveLength(0);});
 it('requires a total for stock deltas and an exact product for writes',()=>{const state=seed();for(const message of ['Add 50 more stock to SKU-101','Set stock to 50']){const intent=quickIntent(state,message);if(intent)expect(intent.run(state,'user','en').action).toBeUndefined();}const action=quickIntent(state,'Set SKU-101 stock to 50')!.run(state,'user','en').action!;expect(action.args.stock).toBe(50);expect(state.products[0].stock).not.toBe(50);});
 it('keeps courier handover distinct from packing',()=>{const result=quickIntent(seed(),'Order LP 8042 dispatch kar diya')!.run(seed(),'user','en');expect(result.action).toBeUndefined();expect(result.text).toContain('Courier handover');});
});
describe('incremental answer transport',()=>{
 it('holds unfinished sentences and avoids breaking decimal numbers',()=>{expect(takeSentences('Price is 1.5 rupees. Next')).toEqual({parts:['Price is 1.5 rupees.'],rest:'Next'});expect(takeSentences('आज चार ऑर्डर हैं। अगला')).toEqual({parts:['आज चार ऑर्डर हैं।'],rest:'अगला'});expect(takeSentences('unfinished')).toEqual({parts:[],rest:'unfinished'});});
 it('keeps internal names out of full replies and token-split streams',()=>{expect(cleanReply('get_commitment_decision says Hold','hi')).toBe('तैयारी की समीक्षा says Hold');const deltas:string[]=[];const stream=new ReplyTextStream('hi',text=>deltas.push(text));for(const text of ['The get_', 'commitment_', 'decision says ', 'Hold.'])stream.push(text);stream.finish();expect(deltas.join('')).toBe('The तैयारी की समीक्षा says Hold.');expect(deltas.some(text=>text.includes('get_'))).toBe(false);});
 it('removes formatting from spoken text',()=>{expect(cleanSpeech('**Four orders** — [Open](/orders)')).toBe('Four orders, Open');});
 it('decodes Hindi and events across arbitrary network chunk boundaries',async()=>{const bytes=new TextEncoder().encode('पहला\nsecond\n');const stream=new ReadableStream<Uint8Array>({start(controller){for(let i=0;i<bytes.length;i+=2)controller.enqueue(bytes.slice(i,i+2));controller.close();}});const result=[];for await(const line of lines(stream))result.push(line);expect(result).toEqual(['पहला','second']);});
});
