'use client';
import {useEffect,useRef,useState} from 'react';
import {Mic,Send,X,Volume2,Square,ArrowRight} from 'lucide-react';
import {usePathname,useRouter} from 'next/navigation';
import {Action} from '@/lib/types';
import {api} from './ui';
import {matchingVoice,speechRetryAt,waitForVoices} from '@/lib/speech-client';
import {responseLanguage,translate} from '@/lib/i18n';
type Reply={text:string;spoken:string;provider:string;language?:string;route?:string;action?:Action;records?:unknown[]};
export default function Voice({language,onClose,onAction,initial='',onField}:{language:string;onClose:()=>void;onAction:(a:Action)=>void;initial?:string;onField?:(text:string)=>void}){const t=(s:string)=>translate(language,s),router=useRouter(),pathname=usePathname();const [input,setInput]=useState(initial),[status,setStatus]=useState('Idle'),[error,setError]=useState(''),[messages,setMessages]=useState<{role:string;text:string;reply?:Reply}[]>([]),[aloud,setAloud]=useState(false),[transcriptLanguage,setTranscriptLanguage]=useState<string|null>(null),[speechNotice,setSpeechNotice]=useState('');const recording=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),chunks=useRef<Blob[]>([]),timer=useRef<ReturnType<typeof setTimeout>|null>(null),start=useRef(0),request=useRef(0),lastAudio=useRef<{blob:Blob;duration:number}|null>(null),audio=useRef<HTMLAudioElement|null>(null),objectUrl=useRef(''),speechSequence=useRef(0),cloudRetryAt=useRef(0);
 const cleanup=()=>{stream.current?.getTracks().forEach(t=>t.stop());if(timer.current)clearTimeout(timer.current);};
 const stopSpeech=()=>{speechSequence.current++;audio.current?.pause();window.speechSynthesis?.cancel();if(objectUrl.current)URL.revokeObjectURL(objectUrl.current);};
 useEffect(()=>{setAloud(localStorage.getItem('lp-read-aloud')==='true');const requestSequence=request,speakingSequence=speechSequence;return()=>{requestSequence.current++;speakingSequence.current++;if(recording.current?.state==='recording'){recording.current.onstop=null;recording.current.stop();}cleanup();audio.current?.pause();window.speechSynthesis?.cancel();if(objectUrl.current)URL.revokeObjectURL(objectUrl.current);};},[pathname]);
 async function playback(text:string,id:number,speechLanguage:string){
  if(!aloud)return;stopSpeech();const sequence=speechSequence.current;setSpeechNotice('');setStatus('Speaking');
  const current=()=>id===request.current&&sequence===speechSequence.current;
  let browserFallback=true,deviceStarted=false;
  try{
   if(Date.now()>=cloudRetryAt.current){
    const r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:text.slice(0,600),language:speechLanguage})});
    if(!current())return;
    if(r.ok){const blob=await r.blob();if(!blob.size)throw new Error('Cloud speech returned empty audio.');if(!current())return;objectUrl.current=URL.createObjectURL(blob);audio.current=new Audio(objectUrl.current);audio.current.onended=()=>{if(current())setStatus('Idle');};audio.current.onerror=()=>{if(current()){setSpeechNotice('Cloud audio could not play. Trying a matching device voice.');void deviceSpeech();}};await audio.current.play();return;}
    const data=await r.json();browserFallback=data.browserFallback!==false;
    cloudRetryAt.current=speechRetryAt(r.status,r.headers.get('Retry-After'));
    setSpeechNotice(r.status===429?'Cloud speech has reached its allowance. Using a matching device voice.':'Cloud speech is unavailable. Trying a matching device voice.');
   }else setSpeechNotice('Using device speech while cloud speech recovers.');
  }catch{if(!current())return;setSpeechNotice('Cloud speech could not play. Trying a matching device voice.');}
  if(!current())return;
  if(!browserFallback||!window.speechSynthesis){setSpeechNotice('Speech is unavailable here. Your text answer is ready.');setStatus('Idle');return;}
  await deviceSpeech();
  async function deviceSpeech(){
   if(!current()||deviceStarted)return;deviceStarted=true;
  const voices=await waitForVoices(window.speechSynthesis);if(!current())return;
  const voice=matchingVoice(voices,speechLanguage);
  if(!voice){setSpeechNotice('No matching '+speechLanguage+' voice is installed on this device. Your text answer is ready.');setStatus('Idle');return;}
  const utterance=new SpeechSynthesisUtterance(text);utterance.voice=voice;utterance.lang=voice.lang;
  utterance.onend=()=>{if(current())setStatus('Idle');};
  utterance.onerror=()=>{if(current()){setSpeechNotice('Device speech could not play. Your text answer is ready.');setStatus('Idle');}};
  window.speechSynthesis.speak(utterance);
  }
 }
 async function send(){if(!input.trim()||['Understanding','Transcribing'].includes(status))return;stopSpeech();const id=++request.current;setError('');setSpeechNotice('');setStatus('Understanding');const text=input;const requestLanguage=responseLanguage(text,language,transcriptLanguage);setMessages(m=>[...m,{role:'user',text}]);setInput('');try{const reply=await api<Reply>('assistant',{message:text,language:requestLanguage});if(id!==request.current)return;setStatus('Fetching information');setMessages(m=>[...m,{role:'assistant',text:reply.text,reply}]);if(reply.action)onAction(reply.action);setStatus('Idle');await playback(reply.spoken,id,reply.language??requestLanguage);}catch(e){if(id===request.current){setError(e instanceof Error?e.message:'Assistant unavailable');setStatus('Error');}}}
 async function transcribe(blob:Blob,duration:number,id:number){setStatus('Transcribing');lastAudio.current={blob,duration};try{if(blob.size===0)throw new Error('No audio recorded. Try again.');if(blob.size>3000000)throw new Error('Audio is over 3 MB. Record a shorter message.');const f=new FormData();f.append('audio',blob,'recording.'+(blob.type.includes('mp4')?'mp4':blob.type.includes('ogg')?'ogg':'webm'));f.append('duration',String(Math.min(45,duration)));const r=await fetch('/api/stt',{method:'POST',body:f});const d=await r.json();if(id!==request.current)return;if(!r.ok)throw new Error(d.error);setTranscriptLanguage(d.language??null);setInput(d.text);onField?.(d.text);setStatus('Idle');}catch(e){if(id===request.current){setError(e instanceof Error?e.message:'Transcription failed');setStatus('Error');}}}
 async function record(){const id=++request.current;setError('');stopSpeech();setStatus('Requesting permission');try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('This browser cannot record audio. Please type your question.');const media=await navigator.mediaDevices.getUserMedia({audio:true});if(id!==request.current){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus','audio/webm'].find(m=>MediaRecorder.isTypeSupported(m));if(!mime)throw new Error('No supported recording format. Please type your question.');const rec=new MediaRecorder(media,{mimeType:mime,audioBitsPerSecond:64000});recording.current=rec;chunks.current=[];start.current=Date.now();rec.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data);};rec.onerror=()=>{cleanup();setError('Microphone recording failed.');setStatus('Error');};rec.onstop=()=>{cleanup();if(id===request.current)void transcribe(new Blob(chunks.current,{type:mime}),(Date.now()-start.current)/1000,id);};rec.start();setStatus('Listening');timer.current=setTimeout(()=>{if(rec.state==='recording')rec.stop();},45000);}catch(e){cleanup();setError(e instanceof DOMException&&e.name==='NotAllowedError'?'Microphone permission denied. You can still type below.':e instanceof Error?e.message:'No microphone found');setStatus('Error');}}
 function cancel(){request.current++;if(recording.current?.state==='recording')recording.current.stop();cleanup();stopSpeech();setStatus('Idle');}
 return <aside className="assistant" aria-label="Launchpad assistant"><div className="assistant-head"><div><span className="eyebrow">YOUR OPERATING ASSISTANT</span><h2>{t('Ask Launchpad')}</h2></div><button className="icon" aria-label="Close assistant" onClick={onClose}><X size={20}/></button></div><div className="assistant-body"><p className="muted">Ask about orders, stock or your next production decision. Changes always need your confirmation.</p>{!messages.length&&<div className="suggestions">{['Aaj kitne orders bhejne hain?','Which products are running low?','Next week bedsheet ki demand kitni ho sakti hai?'].map(q=><button key={q} onClick={()=>{setTranscriptLanguage(null);setInput(q);}}>{q}<ArrowRight size={16}/></button>)}</div>}{messages.map((m,i)=><div className={'message '+(m.role==='assistant'?'assistant-message':'user-message')} key={i}><small>{m.role==='user'?'You':m.reply?.provider}</small><p>{m.text}</p>{m.reply?.route&&<button onClick={()=>router.push(m.reply!.route!)}>{t('Open')}<ArrowRight size={16}/></button>}{m.reply?.records&&<details><summary>View source records</summary><pre>{JSON.stringify(m.reply.records,(_k,v)=>_k==='action'?undefined:v,2)}</pre></details>}</div>)}</div><div className="voice-controls"><div className="voice-status" role="status"><span className={status==='Listening'?'listening-dot':'status-dot'}/>{status} {status==='Listening'&&'· maximum 45 seconds'}</div>{error&&<p className="error" role="alert">{error}</p>}{speechNotice&&<p className="small-note" role="status">{speechNotice}</p>}{lastAudio.current&&status==='Error'&&<button onClick={()=>{setError('');void transcribe(lastAudio.current!.blob,lastAudio.current!.duration,++request.current);}}>{t('Retry transcription')}</button>}<label className="check"><input type="checkbox" checked={aloud} onChange={e=>{setAloud(e.target.checked);localStorage.setItem('lp-read-aloud',String(e.target.checked));if(!e.target.checked){stopSpeech();if(status==='Speaking')setStatus('Idle');}}}/>{t('Read answers aloud')}</label><textarea aria-label={t('Type a question')} value={input} onChange={e=>{setTranscriptLanguage(null);setInput(e.target.value);}} placeholder={t('Type a question')} rows={3}/><div className="button-row">{status==='Listening'?<><button onClick={()=>recording.current?.stop()}><Square size={16}/>{t('Stop and send')}</button><button onClick={cancel}>{t('Cancel recording')}</button></>:<button onClick={record} disabled={status==='Transcribing'||status==='Requesting permission'}><Mic size={17}/>Record</button>}<button className="primary" onClick={send} disabled={!input.trim()||status==='Understanding'}><Send size={16}/>{t('Send')}</button></div>{status==='Speaking'&&<button onClick={()=>{stopSpeech();setStatus('Idle');}}><Volume2 size={16}/>{t('Stop speaking')}</button>}<small>Transcription appears here for review before sending.</small></div></aside>;
}
