'use client';
import {useEffect,useRef,useState} from 'react';
import {Mic,Send,X,Volume2,Square,ArrowRight} from 'lucide-react';
import {usePathname,useRouter} from 'next/navigation';
import {Action} from '@/lib/types';
import {api} from './ui';
import {translate} from '@/lib/i18n';
type Reply={text:string;spoken:string;provider:string;route?:string;action?:Action;records?:unknown[]};
export default function Voice({language,onClose,onAction,initial='',onField}:{language:string;onClose:()=>void;onAction:(a:Action)=>void;initial?:string;onField?:(text:string)=>void}){const t=(s:string)=>translate(language,s),router=useRouter(),pathname=usePathname();const [input,setInput]=useState(initial),[status,setStatus]=useState('Idle'),[error,setError]=useState(''),[messages,setMessages]=useState<{role:string;text:string;reply?:Reply}[]>([]),[aloud,setAloud]=useState(false);const recording=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),chunks=useRef<Blob[]>([]),timer=useRef<ReturnType<typeof setTimeout>|null>(null),start=useRef(0),request=useRef(0),lastAudio=useRef<{blob:Blob;duration:number}|null>(null),audio=useRef<HTMLAudioElement|null>(null),objectUrl=useRef('');
 const cleanup=()=>{stream.current?.getTracks().forEach(t=>t.stop());if(timer.current)clearTimeout(timer.current);};
 const stopSpeech=()=>{audio.current?.pause();window.speechSynthesis?.cancel();if(objectUrl.current)URL.revokeObjectURL(objectUrl.current);};
 useEffect(()=>{setAloud(localStorage.getItem('lp-read-aloud')==='true');const requestSequence=request;return()=>{requestSequence.current++;if(recording.current?.state==='recording'){recording.current.onstop=null;recording.current.stop();}cleanup();audio.current?.pause();window.speechSynthesis?.cancel();if(objectUrl.current)URL.revokeObjectURL(objectUrl.current);};},[pathname]);
 async function playback(text:string,id:number){if(!aloud)return;setStatus('Speaking');try{const r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:text.slice(0,600),language})});if(id!==request.current)return;if(r.ok){objectUrl.current=URL.createObjectURL(await r.blob());audio.current=new Audio(objectUrl.current);audio.current.onended=()=>setStatus('Idle');await audio.current.play();return;}const data=await r.json();if(!data.browserFallback)throw new Error(data.error??'Speech unavailable');const voice=window.speechSynthesis?.getVoices().find(v=>v.lang.split('-')[0]===language);if(!voice)throw new Error('No suitable voice for this language on this device. The text answer is available.');const utterance=new SpeechSynthesisUtterance(text);utterance.voice=voice;utterance.lang=voice.lang;utterance.onend=()=>setStatus('Idle');utterance.onerror=()=>{setError('Speech playback was blocked or failed.');setStatus('Error');};window.speechSynthesis.speak(utterance);}catch(e){setError(e instanceof Error?e.message:'Speech unavailable');setStatus('Error');}}
 async function send(){if(!input.trim()||['Understanding','Transcribing'].includes(status))return;const id=++request.current;setError('');setStatus('Understanding');const text=input;setMessages(m=>[...m,{role:'user',text}]);setInput('');try{const reply=await api<Reply>('assistant',{message:text,language});if(id!==request.current)return;setStatus('Fetching information');setMessages(m=>[...m,{role:'assistant',text:reply.text,reply}]);if(reply.action)onAction(reply.action);setStatus('Idle');await playback(reply.spoken,id);}catch(e){if(id===request.current){setError(e instanceof Error?e.message:'Assistant unavailable');setStatus('Error');}}}
 async function transcribe(blob:Blob,duration:number,id:number){setStatus('Transcribing');lastAudio.current={blob,duration};try{if(blob.size===0)throw new Error('No audio recorded. Try again.');if(blob.size>3000000)throw new Error('Audio is over 3 MB. Record a shorter message.');const f=new FormData();f.append('audio',blob,'recording.'+(blob.type.includes('mp4')?'mp4':'webm'));f.append('duration',String(Math.min(45,duration)));const r=await fetch('/api/stt',{method:'POST',body:f});const d=await r.json();if(id!==request.current)return;if(!r.ok)throw new Error(d.error);setInput(d.text);onField?.(d.text);setStatus('Idle');}catch(e){if(id===request.current){setError(e instanceof Error?e.message:'Transcription failed');setStatus('Error');}}}
 async function record(){const id=++request.current;setError('');stopSpeech();setStatus('Requesting permission');try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('This browser cannot record audio. Please type your question.');const media=await navigator.mediaDevices.getUserMedia({audio:true});if(id!==request.current){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus','audio/webm'].find(m=>MediaRecorder.isTypeSupported(m));if(!mime)throw new Error('No supported recording format. Please type your question.');const rec=new MediaRecorder(media,{mimeType:mime,audioBitsPerSecond:64000});recording.current=rec;chunks.current=[];start.current=Date.now();rec.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data);};rec.onerror=()=>{cleanup();setError('Microphone recording failed.');setStatus('Error');};rec.onstop=()=>{cleanup();if(id===request.current)void transcribe(new Blob(chunks.current,{type:mime}),(Date.now()-start.current)/1000,id);};rec.start();setStatus('Listening');timer.current=setTimeout(()=>{if(rec.state==='recording')rec.stop();},45000);}catch(e){cleanup();setError(e instanceof DOMException&&e.name==='NotAllowedError'?'Microphone permission denied. You can still type below.':e instanceof Error?e.message:'No microphone found');setStatus('Error');}}
 function cancel(){request.current++;if(recording.current?.state==='recording')recording.current.stop();cleanup();stopSpeech();setStatus('Idle');}
 return <aside className="assistant" aria-label="Launchpad assistant"><div className="assistant-head"><div><span className="eyebrow">YOUR OPERATING ASSISTANT</span><h2>{t('Ask Launchpad')}</h2></div><button className="icon" aria-label="Close assistant" onClick={onClose}><X size={20}/></button></div><div className="assistant-body"><p className="muted">Ask about orders, stock or your next production decision. Changes always need your confirmation.</p>{!messages.length&&<div className="suggestions">{['Aaj kitne orders bhejne hain?','Which products are running low?','Next week bedsheet ki demand kitni ho sakti hai?'].map(q=><button key={q} onClick={()=>setInput(q)}>{q}<ArrowRight size={16}/></button>)}</div>}{messages.map((m,i)=><div className={'message '+(m.role==='assistant'?'assistant-message':'user-message')} key={i}><small>{m.role==='user'?'You':m.reply?.provider}</small><p>{m.text}</p>{m.reply?.route&&<button onClick={()=>router.push(m.reply!.route!)}>{t('Open')}<ArrowRight size={16}/></button>}{m.reply?.records&&<details><summary>View source records</summary><pre>{JSON.stringify(m.reply.records,(_k,v)=>_k==='action'?undefined:v,2)}</pre></details>}</div>)}</div><div className="voice-controls"><div className="voice-status" role="status"><span className={status==='Listening'?'listening-dot':'status-dot'}/>{status} {status==='Listening'&&'· maximum 45 seconds'}</div>{error&&<p className="error" role="alert">{error}</p>}{lastAudio.current&&status==='Error'&&<button onClick={()=>{setError('');void transcribe(lastAudio.current!.blob,lastAudio.current!.duration,++request.current);}}>{t('Retry transcription')}</button>}<label className="check"><input type="checkbox" checked={aloud} onChange={e=>{setAloud(e.target.checked);localStorage.setItem('lp-read-aloud',String(e.target.checked));if(!e.target.checked)stopSpeech();}}/>{t('Read answers aloud')}</label><textarea aria-label={t('Type a question')} value={input} onChange={e=>setInput(e.target.value)} placeholder={t('Type a question')} rows={3}/><div className="button-row">{status==='Listening'?<><button onClick={()=>recording.current?.stop()}><Square size={16}/>{t('Stop and send')}</button><button onClick={cancel}>{t('Cancel recording')}</button></>:<button onClick={record} disabled={status==='Transcribing'||status==='Requesting permission'}><Mic size={17}/>Record</button>}<button className="primary" onClick={send} disabled={!input.trim()||status==='Understanding'}><Send size={16}/>{t('Send')}</button></div>{status==='Speaking'&&<button onClick={()=>{stopSpeech();setStatus('Idle');}}><Volume2 size={16}/>{t('Stop speaking')}</button>}<small>Transcription appears here for review before sending.</small></div></aside>;
}
